### PR TITLE
Some cleanup

### PR DESCRIPTION
**Pull request by Bo98**
* Made use of ply:getJobTable(), ply:isMayor() and ply:isChief() internally.
  - A lot less repetitive RPExtraTeam checking.
* Simplified drug timer code.
* Shifted weirdly placed HUD IsValid check.
* Got rid of useless ent.ShareGravgun.
* Fixed some typos/old comments.
* Some spacing, ent:GetTable() and dead code cleanup.

### CODE REVIEW

**Comment by LetsRaceBwoi** [comment]
why 8 PRs? can't you just use one? ._.

**Comment by fruitwasp** [comment]
Much cleaner than just one.

**Comment by Bo98** [comment]
It's up to @FPtje I guess. I thought splitting it up would make it a bit easier to keep track of the changes but I could easily shove it all into one if that is preferred.

**Comment by Bo98** [comment]
I also felt a bit sorry after #985.

**Comment by NamefuI** [comment]
@Bo98 I don't know if it's that you have so much spare time or you're just bored.
No matter what, your work is truly beautiful, thank you <3

**Comment by HDG-MrDeeJay** [comment]
Holy shit, I've been ... posting... on this repo for like 2 years now.

**Comment by Bo98** [comment]
I just realised #985 was exactly 2 years ago yesterday.

**Comment by FPtje** [comment]
I prefer separate prs, yes

**Pull request merged**
