### PR TITLE
Fixed some singleplayer issues with the batons

### PR DESCRIPTION
**Pull request by Bo98**
Singleplayer is a horrible, horrible place. I would add:

```lua
if game.SinglePlayer() then error("Use a listen server.") end
```

to init.lua if I had my own way.

Fixes http://forum.darkrp.com/threads/baton-glitch.4924/.

### CODE REVIEW

**Comment by Bo98** [comment]
The unarrest_stick part might fix similar reports on servers but god knows how that code is even allowed to run when it is removed on Holster.

But trust someone to find a case that should only happen when the stars align. The stars must align every day for them.

**Comment by HDG-MrDeeJay** [comment]
reminds me of a friend who could find a way to break any game.

**Comment by FPtje** [comment]
Honestly, I don't care much for SinglePlayer either, but completely disabling it is a step too far.

**Comment by Bo98** [comment]
Yeah, I wasn't serious there.

**Pull request merged**
