### PR TITLE
added DarkRP.getJobTable(id)

### PR DESCRIPTION
**Pull request by fruitwasp**

### CODE REVIEW

**Comment by FPtje** [comment]
Why?

**Comment by uRandomAlex** [comment]
@FPtje It's very useful in hooks like "playerCanChangeTeam", for example. I can't think of any other way to get job table there.

**Comment by Bo98** [comment]
I suppose you could argue there should've been API to return RPExtraTeam rather than using a global variable but it's far too late for that and this pull request only half finishes the job.

**Comment by FPtje** [comment]
Good point.

**Pull request closed without merging**
