### PR TITLE
Add a delay option

### PR DESCRIPTION
**Pull request by BLEEPBLOOPforLife**
Adds a delay option in custom entity creation with tblEnt.delay and adds validation for the delay option.

### CODE REVIEW

**Comment by BLEEPBLOOPforLife** [comment]
So, is this being added?

**Comment by FPtje** [comment]
I usually use weekends to work on DarkRP. I'll look at this later today.

**Comment by BLEEPBLOOPforLife** [comment]
Got it.

**Comment by FPtje** [comment]
Merged. Some feedback: 

Use more descriptive names than "Updated <file.lua>". Also, it should have been a single commit. The idea of a commit is that it describes a unit of change over the entire repository. Ideally, DarkRP should work properly at every commit in history. In this case the change is split into two commits, creating a point in the commit history where a commit is half implemented. In this case that won't lead to errors, but in more sophisticated changes it might.

Regardless, I'm happy with the contribution. The delay of two seconds isn't ideal for every entity's chat command, and you're right in that it should be possible to set it per entity.

**Comment by Kefta** [comment]
@FPtje As repository owner, you can squash all commits on merge.

**Comment by FPtje** [comment]
I know

**Comment by BLEEPBLOOPforLife** [comment]
Alright. Will do next time.

**Pull request merged**
