### PR TITLE
Fixed gamemode not changing

### PR DESCRIPTION
**Pull request by TheEMP**
Changegamemode doesn't exist in Garry's Mod 13.

### CODE REVIEW

**Comment by Bo98** [comment]
You can move the changelevel command out of the if statement for a little less code duplication.

**Comment by HDG-MrDeeJay** [comment]
am I high, or is github saying OP and you have the same surnames Bo?

**Comment by Bo98** [comment]
Anderson isn't an uncommon surname.

**Comment by HDG-MrDeeJay** [comment]
Guess you all have a hell of a laugh when someone calls your name.

Mr Anderson

**Comment by Bo98** [comment]
I get the Mr Anderson comment a lot.

**Comment by HDG-MrDeeJay** [comment]
I can imagine. I too, get a lot of comments on my last name. Most people think Davies is a middle name, and then ask me if I have a working visa because Lee sounds like Li and Li is a common asian last name.

**Comment by TheEMP** [comment]
I get the Mr Anderson comment all the time haha. I'll move the changelevel outside the if statment I didn't even think of that.

**Comment by FPtje** [comment]
I've got multiple, "do a barrel roll" and "Falcon punch" are the most
common ones.

**Pull request merged**
