### PR TITLE
Fixed #1957

### LINKED ISSUE #1957: Error stuntick
[ERROR] gamemodes/darkrp/entities/weapons/stunstick/shared.lua:92: attempt to index local 'attachment' (a nil value)
  1. unknown - gamemodes/darkrp/entities/weapons/stunstick/shared.lua:92

### PR DESCRIPTION
**Pull request by TylerGeorges**
Credit to @00875 for helping fix it.

### CODE REVIEW

**Comment by FPtje** [comment]
Why did you replace all tabs with spaces?

**Comment by 00875** [comment]
This is not a solution, but workaround

**Comment by fruitwasp** [comment]
Why don't you ```return``` if ```achievements == nil```, instead of that tree?

**Comment by 00875** [comment]
If code was more longer, i will use return

**Comment by FPtje** [comment]
#1963 
Sorry you got overruled, but @Bo98 has the better solution.

**Pull request closed without merging**
