### PR TITLE
Update sv_gamemode_functions.lua

### PR DESCRIPTION
**Pull request by cardentity**
+Performance

### CODE REVIEW

**Comment by FPtje** [comment]
Hmm, I get the idea of the pr: DarkRP shouldn't try to regain ownership if the player is not "rejoining". My gut says there should be a more elegant way to solve, this, though.

**Comment by cardentity** [comment]
Good idea. But now it being better than nothing.

**Comment by FPtje** [comment]
I'm looking at it right now. Why should it loop over all entities in the
first place?

**Comment by cardentity** [comment]
It set own "disconnected player" entities. I moved it into "if"

**Comment by FPtje** [comment]
It still loops over all entities. Besides, one timer per entity is not clever performance wise. Like I said, I'm looking at it.

**Comment by cardentity** [comment]
Yep.

**Comment by FPtje** [comment]
Alright, sorry for not merging your thing, but thanks a lot for the pr anyway. Bringing this up was important. 

Here's what I've improved:
- On disconnected, it loops over all entities once instead of *once for every custom entity*
- Instead of a timer per entity (and player), there is now one timer per player. More timers = less performance. 
- on PlayerInitialSpawn it only loops over the entities that were queued to be removed. It also skips this if the player hasn't played recently, thanks to your pr. 

Thanks a lot for this pr!

**Comment by cardentity** [comment]
No reason to apologize :)

**Pull request closed without merging**
