### PR TITLE
Localize vector constants

### PR DESCRIPTION
**Pull request by djtb2924**
I know it's micro-optimisation but why not.

Just localizing vector before loops

### CODE REVIEW

**Comment by mcNuggets1** [comment]
Maybe we should use Player:GetHull() for this anyways?
Servers wo use the playerscale module would appreciate.

**Comment by FlorianLeChat** [comment]
I'm not sure but `ply:SetHull` (or a kind of collisions update) isn't called automatically after `ply:SetModelScale` since the last update?

**Comment by mcNuggets1** [comment]
Obviously.
ModelScale and Hull is different.
It never updated Hull, as far as I'm concerned.

**Comment by FPtje** [comment]
Thanks!

**Pull request merged**
