### PR TITLE
Added support for destroying func_breakable_surf

### PR DESCRIPTION
**Pull request by deinemudda32**
support for destroying func_breakable_surf for probably police raids :)

### CODE REVIEW

**Comment by HDG-MrDeeJay** [comment]
so stuff like custom(shitty) windows that take more than a love-tap to 
break?

**Comment by deinemudda32** [comment]
what do you mean?
func_breakable_surf are standard half life 2 windows, seen in alot of RP maps.

**Comment by FPtje** [comment]
Why the C syntax and the mix between spaces and tabs though?

**Comment by deinemudda32** [comment]
I like it tidy.

**Comment by FPtje** [comment]
Well I like it consistent with the rest of DarkRP.

**Comment by deinemudda32** [comment]
But how is the idea to make func_breakable_surf destroyable? ._.

**Comment by FPtje** [comment]
Is it possible in another way than bullets?

**Comment by HDG-MrDeeJay** [comment]
Terrible. If its standard HL2 windows, they should be breakable anyway 
just by tapping it. They are brittle as fuck.

**Comment by deinemudda32** [comment]
I tried alot in singleplayer but nothing seemed to work to get it breakable.
If you got another way, tell me :)

**Comment by HDG-MrDeeJay** [comment]
Yes. Props, a fast moving player, vehicles.

**Comment by deinemudda32** [comment]
I did mean with the weapon?
Should the weapon throw a washing machine or what?
Or a moving player or a jeep?

**Comment by FPtje** [comment]
You'd expect a crowbar to hit a hole in the glass, but not a stunstick. The
stunstick is electricity based. There should be some way to break the glass
without poking a hole in it.

**Comment by HDG-MrDeeJay** [comment]
I'd still expect a stunstick to break the glass

You gotta remember, Valve designed breakable glass to not only represent the sheer power that the HEV suit can output in strength (in comparison to a standard human), but also to represent old, brittle glass. This is why I'm more partial to map developers making their own (transparent) entities that are breakable, to act as glass. Can be taken out one hit without fracturing, can be moved around without hassle, and is easier to work with from the lua end.

**Comment by deinemudda32** [comment]
Maybe a stunning impact?

**Comment by HDG-MrDeeJay** [comment]
Wait just to be clear, we are talking about the same windows right? Those ones that are used in Downtown_v4c all the time, that respawn (even if not needed) every 5 minutes?

**Comment by FPtje** [comment]
Break the glass with its electricity, not with its impact.

Sometimes when you throw a prop near a window, the glass shatters, but it's
still in the window without holes. Kind of like fractured car glass. That
would look a lot cooler than a hole in the glass.

**Comment by HDG-MrDeeJay** [comment]
>Maybe a stunning impact?

Nah, think more like you take the handle of your batton, and apply direct force through the hilt into the center of the window.

**Comment by HDG-MrDeeJay** [comment]
I don't think I'm on the same page as everybody

**Comment by FPtje** [comment]
There's no animation for that.

**Comment by deinemudda32** [comment]
Maybe not skin it blue.
I personally think, thats the main case that it doesnt look and feel like a stun baton

**Comment by FPtje** [comment]
We weren't discussing whether it looks like a stunstick.

**Comment by deinemudda32** [comment]
Yeah right, sorry but I hate that.
Im trying in singleplayer to get this solved.

**Comment by Bo98** [comment]
func_breakabale_surf has an input called "Shatter" that takes a Vector.

**Comment by FPtje** [comment]
Nice

**Comment by deinemudda32** [comment]
Got it working:
So how do I post code?

**Comment by FPtje** [comment]
This is what I meant

**Comment by FPtje** [comment]
Also, you're changing *my* code in the pull request. Get your damn act together.

**Pull request closed without merging**
