### PR TITLE
Duplicate of local error = error

### PR DESCRIPTION
**Pull request by l-Rocky-l**
There was 2 wasnt sure if this was on accident, but Im just informing you!

### CODE REVIEW

**Comment by HDG-MrDeeJay** [comment]
Nice find, it shouldn't be duplicated as far as I can tell.

**Comment by Bo98** [comment]
Should really have been done in the [FPtje/simplerr](https://github.com/FPtje/simplerr) repo though.

**Comment by FPtje** [comment]
Oh I thought this was the simplerr repo. God damnit email links

**Comment by HDG-MrDeeJay** [comment]
Yeah, but all DarkRP repo emails start with [DarkRP] or Re: [DarkRP], so 
perhaps you can create filtering rules in your inbox? I've done that on 
mine using Thunderbird.

**Comment by FPtje** [comment]
Pffft effort

**Comment by HDG-MrDeeJay** [comment]
too much effort to complain about too much effort to look for [DarkRP] 
in my emails.
too much effort to consider easy ways to know whats what
too much effort to write this email
too much effort to click send.

**Comment by HDG-MrDeeJay** [comment]
Because apparently I cannot add markdown to an email reply...

image of how to mail filter

**Comment by Bo98** [comment]
What sort of theme is that?

**Comment by FPtje** [comment]
Take a look at that theme!

**Comment by HDG-MrDeeJay** [comment]
Yeah, its called "Black on Blue", or "GUYS DUBSTEP RAVE MY OC SUPER 
POWERS LEL"

**Comment by l-Rocky-l** [comment]
I DID SO MUCH RIGHT!!!!!!!

IM THE BEST CODA EVA(not even)

**Pull request merged**
