### PR TITLE
add method customEntityCount

### LINKED ISSUE #3084: Expose maxEntities
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
I was wanting to restrict access to cop jobs if players already had money printers spawned.
Exposing the maxEntities table as a global would solve my issue.
https://github.com/FPtje/DarkRP/blob/35ca64069be4e090604544d9fe8a4b41aafeba87/gamemode/modules/base/sv_entityvars.lua#L223

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
This is a feature request.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
N/A

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
It's not possible to achieve what I want without editing the core files, which the developer of DarkRP strongly suggests against.

### PR DESCRIPTION
**Pull request by someoneyouspite**
Resolves #3084

### CODE REVIEW

**Comment by FPtje** [comment]
Thanks! Could you add a function stub!

**Comment by FPtje** [comment]
That exclamation mark was supposed to be a question mark* :see_no_evil:

**Comment by someoneyouspite** [comment]
Will do.

**Comment by Kefta** [comment]
You should not treat the parameter as optional, it will just lead to silent errors. Instead, you should implement it as
```Lua
local entities = maxEntities[self]
if entities == nil then return 0 end

entities = entities[entTable.cmd]
if entities == nil then return 0 end

return entities
```
This is the most efficient impl and the most intuitive to read imo. You could also exchange the last ``== nil`` statement for ``return entities or 0``, but this is not type safe since Lua doesn't have real ternary operators, but to each their own.

The optional parameter discrepancy should also be fixed in ``addCustomEntity`` and ``removeCustomEntity``.

**Comment by someoneyouspite** [comment]
It could still error if passed a non-table for entTable, should I make sure it's type safe like the following?

```lua
    local entities = maxEntities[self]
    if entities == nil then return 0 end

    if type(entTable) == "table" then
        entities = entities[entTable.cmd]
    end
    if entities == nil then return 0 end

    return entities
```

**Comment by Kefta** [comment]
No, the DarkRP API does almost no type checking for its arguments across the codebase so you should assume the passed arg is a table. If a table isn't passed, an error (not a very helpful one but it's better than no error) will occur. This should change in the future when proper CheckType functions are added to GMod's API.

**Comment by FoksVHox** [comment]
> No, the DarkRP API does almost no type checking for its arguments across the codebase so you should assume the passed arg is a table. If a table isn't passed, an error (not a very helpful one but it's better than no error) will occur. This should change in the future when proper CheckType functions are added to GMod's API.

Has there been any talk about that?

**Comment by Kefta** [comment]
> > No, the DarkRP API does almost no type checking for its arguments across the codebase so you should assume the passed arg is a table. If a table isn't passed, an error (not a very helpful one but it's better than no error) will occur. This should change in the future when proper CheckType functions are added to GMod's API.
> 
> Has there been any talk about that?

I have added them with the new sandboxed GMod Lua API, but there are currently issues with pushing it as it relies on C++20 which is incompatible with Steam runtime. I would not count on them being released immediately, so for now, the solution I posted above is the best implementation.

**Comment by someoneyouspite** [comment]
Do you want me to fix the optional parameters in `addCustomEntity`, `removeCustomEntity`, and `customEntityLimitReached` as well?
They all contain this snippet.
```lua
maxEntities[self] = maxEntities[self] or {}
maxEntities[self][entTable.cmd] = maxEntities[self][entTable.cmd] or 0
```
I was considering replacing them with the following.
```lua
if maxEntities[self] == nil then
    maxEntities[self] = {}
end
if maxEntities[self][entTable.cmd] == nil then
    maxEntities[self][entTable.cmd] = 0
end
```

**Comment by FoksVHox** [comment]
> ```lua
> if maxEntities[self] == nil then
>     maxEntities[self] = {}
> end
> if maxEntities[self][entTable.cmd] == nil then
>     maxEntities[self][entTable.cmd] = 0
> end
> ```
That's just a mess, the one above would result in cleaner code.

**Comment by someoneyouspite** [comment]
I would agree in this case, yet I'm not suggesting the fix.

**Comment by Kefta** [comment]
I was referring to
```Lua
if not entTable then return end
```
and
```Lua
if not entTable.cmd then return end
```
Those lines should be removed.

**Review by Kefta — APPROVED** [review]

**Comment by someoneyouspite** [comment]
Fixed the bad commit message, shouldn't be doing pull requests at 4 am. 🤦

**Comment by FPtje** [comment]
Thanks for the effort! Code looks good!

**Pull request merged**
