### PR TITLE
Fix rare clientside error

### PR DESCRIPTION
**Pull request by mcNuggets1**
Very rare error.

### CODE REVIEW

**Comment by FPtje** [comment]
`getJobTable` throws a descriptive error when the job table does not exist. How would this error be possible?

**Comment by mcNuggets1** [comment]
It's extremely rare and clientside only.
Its upon joining a dedicated Server game, the error message is non descriptive and not possible to track or fix.
This will get rid of this rare error.

**Comment by FPtje** [comment]
What is the error message? Does it complain about jobTable being nil? Who is running those functions before join finished? Some join menu script?

**Comment by mcNuggets1** [comment]
[ERROR] gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23: attempt to index local 'jobTable' (a nil value)
  1. Call - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23
   2. unknown - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:62

This is the message.

**Comment by mcNuggets1** [comment]
Its while joining, i dont know why, it cant be traced.
Its gmod at its best.

**Comment by DBotThePony** [comment]
it will still throw an error since you still index `jobTable` inside your `if` condition

**Comment by mcNuggets1** [comment]
It checks if jobTable exists tho in the first place, which the error pinpoints, it doesn't.
Happens on newest 64 bit.
If its not existing and not indexiert, its not erroring.

**Comment by DBotThePony** [comment]
I can only assume this happen when player spam F4 on loading screen and short time after, somehow before player receive their team number

**Comment by FPtje** [comment]
I think I understand why:
https://github.com/FPtje/DarkRP/blob/27d33d7aaf26288e96507cb590ad0ec92958b1a1/gamemode/modules/base/sh_createitems.lua#L396

getJobTable doesn't throw an error when the player is not yet initialized. Could you change the condition to use that same initialized variable and add comment why it's there? That's much better than just the jobTable check imo.

**Comment by mcNuggets1** [comment]
I may misunderstand you, but are you asking me to add a check for a servside value in a clientside environment, which didn't receive said value to check if the player is initialized?

**Comment by FPtje** [comment]
If that var does not exist clientside then it will never throw that error clientside. That's a deeper problem to solve.

**Comment by mcNuggets1** [comment]
That's a serverside var for initializing database stuff onto the player.
I looked everywhere for it clientside, it's not there.

This can't error clientside.

**Comment by FPtje** [comment]
Very well. Can you add a comment?

**Comment by mcNuggets1** [comment]
Done.

**Comment by FPtje** [comment]
Thanks!

**Pull request merged**
