### PR TITLE
Improved code on base

### PR DESCRIPTION
**Pull request by Aka7tsu4**
testing uploading

### CODE REVIEW

**Comment by FPtje** [comment]
It's pretty clear to me that this process went wrong.

**Comment by FPtje** [comment]
Pr*

**Comment by Aka7tsu4** [comment]
yes...it's so hard to upload the files! it's saying "we don't support that file type." u_u...

**Comment by FPtje** [comment]
If only you knew how git worked

**Comment by Shigbeard** [comment]
Merge branch 'master' into workshop | 1 of 180 matches
10/10 gr8 improvement.

**Pull request closed without merging**
