### PR TITLE
Add isvalid checks to more loops in doorsystem

### PR DESCRIPTION
**Pull request by mcNuggets1**
Errors otherwise in some occasions.

### CODE REVIEW

**Comment by Bo98** [comment]
I was about to ask why this was only needed now, but I answered my own question: it's because the behaviour of `isKeysOwnable` was changed recently.

**Comment by mcNuggets1** [comment]
Most of the loops already had isvalid checks, but some of them were missing.

**Comment by FPtje** [comment]
Fixes #3004

**Comment by FPtje** [comment]
Great and all, but removing the isvalid check from `isKeysOwnable` caused errors. I'm sure other addons use it as well, and like DarkRP's own code, may depend on that check being there.

It should not have been removed, and I'm re-adding it. Invalid entities are not ownable.

**Comment by mcNuggets1** [comment]
Maybe remove the isvalid checks from the remaining loops then?

**Pull request merged**
