### PR TITLE
Issue removing jobs.

### PR DESCRIPTION
**Pull request by CodedNil**

### CODE REVIEW

**Comment by FPtje** [comment]
DarkRP.getCategories does exactly what you're pull requesting here, with
the added benefit that it doesn't use terrible coding practices.

**Comment by CodedNil** [comment]
getCategories doesnt allow you to directly edit the categories table though, does it? Atleast in what ive tested it doesnt.

**Comment by FPtje** [comment]
It returns the table directly. Why do you want to edit categories anyway?

**Comment by CodedNil** [comment]
Working on a in game job/category viewer, so to have a update button to recreate jobs and categories first needs to remove all old ones.

**Comment by FPtje** [comment]
That should be possible with that function.
local A = DarkRP.getCategoriesthing()
for k, v in pairs(A) do A[i] = nil end

**Comment by Partixel** [comment]
If you want to see what we're working on:

image

**Comment by CodedNil** [comment]
Hmm, must have been setting it wrong, but i was doing that for a while, f4 menu doesnt seem to change without rejoining.

**Comment by FPtje** [comment]
Looks fancy.

**Comment by FPtje** [comment]
Try calling Refresh on the F4 menu panel.
http://wiki.darkrp.com/index.php/Functions/DarkRP/Client/getF4MenuPanel

**Comment by CodedNil** [comment]
Ah perfect, thanks!

**Comment by CodedNil** [comment]
Ran into another problem, on DarkRP.createJob after doing RPExtraTeams = {} it errors saying command isnt unique, checked through the createJob function but i cannot for the life of me understand what the unique() function would do and were it would be storing a list of the unique commands for me to reset?

**Comment by Partixel** [comment]
The command is added into the env table which has no getter?

**Comment by FPtje** [comment]
I'm thinking about a solution.

**Comment by Partixel** [comment]
F4 Menu does not refresh when calling the refresh functions.

The job is registered to DarkRP on the server and client:

PrintTable( DarkRP.getCategories.jobs ) returns this:

http://pastebin.com/uq1gSGuf

**Comment by FPtje** [comment]
How are you removing the jobs?

**Comment by CodedNil** [comment]
RPExtraTeams = {}
DarkRP.getCategories().jobs = {}
if CLIENT and DarkRP.getF4MenuPanel() then
	DarkRP.getF4MenuPanel():Refresh()
end

**Comment by Partixel** [comment]
Cheers.

**Comment by FPtje** [comment]
Tell me what you think of this approach. I'll add it for other custom items too if it's successful.

**Comment by Partixel** [comment]
Works beautifully, thanks!

**Comment by CodedNil** [comment]
Working pretty perfectly, except it doesnt reset hitmanteams, also theres no getter for hitmanteams of any sort.

**Comment by CodedNil** [comment]
Also 2 errors i have gotten, not sure if they're my fault but it doesnt seem like it is.
[ERROR] gamemodes/darkrp/gamemode/modules/f4menu/cl_jobstab.lua:311: attempt to call field 'PerformLayout' (a nil value)

[ERROR] gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:975: attempt to perform arithmetic on local 'i' (a nil value)

**Comment by FPtje** [comment]
That second error is impossible without getting an "attempt to compare number with nil value" first.

**Comment by CodedNil** [comment]
Thats exactly what it was, nothing else but that error multiple times.

**Comment by CodedNil** [comment]
Remaining things ive found that have either no getter or setter are:
Agendas, has a getter but also has a local table without a setter which most things use.
DemoteGroups, has neither getting or setter.

**Comment by FPtje** [comment]
DarkRPAgendas is a global table. ply:getAgenda() returns members of that table.

**Comment by FPtje** [comment]
https://github.com/FPtje/DarkRP/commit/e5a0ed425fb64fc47e7d70ea63c8dc78f5462c7f

**Comment by CodedNil** [comment]
I cant globally remove all agendas though, as to remove all and reset new ones on a change in my system.

**Comment by Partixel** [comment]
getAgendas returns the global table, not the local table

**Comment by Partixel** [comment]
Cheers, thanks for being so quick :)

**Comment by FPtje** [comment]
That's not what she said.

2015-03-28 17:26 GMT+01:00 Partixel <notifications@github.com>:

**Comment by Partixel** [comment]
Well... if only that were true :(

**Comment by HDG-MrDeeJay** [comment]
lol

**Comment by FPtje** [comment]
Haha!

**Comment by CodedNil** [comment]
Is there any way to get the demotegroup name out of the demotegroup table?

**Comment by FPtje** [comment]
There currently isn't.

**Comment by CodedNil** [comment]
Thanks for pretty much being the greatest dev ever :+1:

**Comment by FPtje** [comment]
Thanks!

2015-03-28 18:04 GMT+01:00 CodeNil <notifications@github.com>:

**Comment by CodedNil** [comment]
Ok i am so confused. Got this error again, no clue why or when, obviously from something im calling but:
[ERROR] gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:982: attempt to perform arithmetic on local 'i' (a nil value)
  1. addToCategory - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:982
   2. createJob - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:660
    3. fn - addons/jcreator/lua/v-handle-jcreator/modules/sh_jobhandler.lua:307
     4. Run - addons/ulib/lua/ulib/shared/hook.lua:105
      5. func - addons/jcreator/lua/v-handle-jcreator/libs/vh-datalib.lua:102
       6. unknown - lua/includes/modules/net.lua:32

No other errors. Shouldnt be possible but apparently it is?

**Comment by Partixel** [comment]
Saw it in the server console, can confim

**Comment by FPtje** [comment]
> That second error is impossible without getting an "attempt to compare number with nil value" first.

Please investigate using debug prints. I can't fix an error that's impossible.

**Comment by Partixel** [comment]
We will do, it's just taking a while to get it again.

**Comment by CodedNil** [comment]
Ive no clue what exactly causes it, but i have managed to have a debug in once when it happened, and it printed i as a number like 5 times before causing the error, while i was still a number.

**Comment by Partixel** [comment]
From what I can tell it's a problem with lua and too many local variables ( ? )

This change fixes it:

at line 982 ( straight after the while i > 1 do ) add this:

i = i or 2

**Comment by FPtje** [comment]
Nope, makes no sense.

**Comment by Partixel** [comment]
Well, I know it makes no sense, I don't really know what to say :(

**Comment by Partixel** [comment]
I'm selling my addon on scriptfodder and they're getting the error too:

"Another error has surfaced as well, making jobs not show.
[ERROR] gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:982: attempt to perform arithmetic on local 'i' (a nil value)
1. addToCategory - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:982
2. createJob - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:660
3. RegisterItems - addons/jcreator/lua/v-handle-jcreator/modules/sh_jobhandler.lua:307
4. func - addons/jcreator/lua/v-handle-jcreator/modules/sh_jobhandler.lua:91
5. unknown - lua/includes/modules/net.lua:32"

**Comment by Partixel** [comment]
The error occurs when the createJob function is called multiple ( 50 + ? ) times in succession

**Comment by FPtje** [comment]
Can you email me the calls? I.e. All jobs?

**Comment by Partixel** [comment]
Sent along with the addon.

**Comment by Partixel** [comment]
Are you able to reproduce the error with the stuff I sent you?

**Comment by FPtje** [comment]
I'm starting gmod just now

2015-03-31 13:24 GMT+02:00 Partixel <notifications@github.com>:

**Comment by Partixel** [comment]
Okay great :)

As far as I can tell, i is local so couldn't be overwritten by any other code and nothing is setting it apart from the i = i - 1 so it seems to be an issue with lua itself

**Comment by Partixel** [comment]
If you replace the while loop with this:

		for i = pos, 2, -1 do
			if categoryOrder(c.members[i - 1], item) then break end
			c.members[i - 1], c.members[i] = c.members[i], c.members[i - 1]
		end

and rename the "local i = " to "local pos = " it fixes the error but then this new error occurs:

[ERROR] gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:949: attempt to index local 'a' (a nil value)
  1. categoryOrder - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:949
   2. addToCategory - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:982
    3. createJob - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:660
     4. v - addons/v-handle-jcreator/lua/v-handle-jcreator/modules/sh_jobhandler.lua:308
      5. Run - lua/includes/modules/hook.lua:84
       6. func - addons/v-handle-jcreator/lua/v-handle-jcreator/libs/vh-datalib.lua:162
        7. unknown - lua/includes/modules/net.lua:32

**Comment by Partixel** [comment]
The only working fix I have found so far is to remove the while loop and instead use table.sort within the F4 menu when it is opened

e.g.
line 372 of cl_jobstab.lua add
	table.sort(categories, categoryOrder)

**Comment by FPtje** [comment]
I refuse to fix bugs that cannot exist.

2015-03-31 14:18 GMT+02:00 Partixel <notifications@github.com>:

**Comment by Partixel** [comment]
So you can't replicate it ? Or you can replicate it but are just being stubborn ?

**Comment by FPtje** [comment]
I've seen it once and I can't reproduce it. For all I know your addon could
be doing crazy shit.

2015-03-31 14:23 GMT+02:00 Partixel <notifications@github.com>:

**Comment by Partixel** [comment]
Well, my addon could do all the crazy shit it once, it can't edit local variables though.

**Comment by Partixel** [comment]
I can reproduce the error every time I join my test server, the only addons are the darkrpmodification I sent you and my addon

**Comment by FPtje** [comment]
alright, I'll try on a ds

2015-03-31 14:28 GMT+02:00 Partixel <notifications@github.com>:

**Comment by Partixel** [comment]
I can give you the ip of my test server if you want.

**Comment by FPtje** [comment]
It appears as though the error is reproduced on the ds. More info soon.

**Comment by Partixel** [comment]
Thank gosh, thought I may have been going crazy.

**Comment by FPtje** [comment]
I know I am

2015-03-31 14:42 GMT+02:00 Partixel <notifications@github.com>:

**Comment by FPtje** [comment]
The error happens sometimes on the server, sometimes on the client, sometimes both. As soon as I add a debug print it doesn't error anymore.

**Comment by Partixel** [comment]
Yup, it's annoying as hell.

**Comment by Partixel** [comment]
Using table.sort( c.members, categoryOrder ) fixes the error BUT doesn't actually sort the table.

**Comment by FPtje** [comment]
This issue might be bigger than that.

2015-03-31 14:55 GMT+02:00 Partixel <notifications@github.com>:

**Comment by Partixel** [comment]
It might be bigger then all of us.

**Comment by FPtje** [comment]
http://facepunch.com/showthread.php?t=1450721&p=47429165&viewfull=1#post47429165

**Comment by Partixel** [comment]
Love the post, although, this fix doesn't actually sort the table, try setting a jobs sortOrder to 0 and then checking it's position in the F4 menu

**Comment by FPtje** [comment]
That works fine for me when that jc thing isn't installed. It doesn't work when it is. I've tested both categories and individual jobs. That might be because your jc thing loads jobs from text files on startup.

Editing the jobs.lua file has no effect when your mod is installed.

**Comment by Partixel** [comment]
Sorry, I meant, when before it would error, it now just doesn't edit the table.

**Comment by Partixel** [comment]
Edit the jobs sortOrder via 'jc_menu' > jobs > any job > sortOrder

**Comment by Partixel** [comment]
When I sort it as the F4 menu is opened it sorts correctly and I've checked sortOrder is set correct on the client

**Comment by FPtje** [comment]
I tested it without your addon and it works. If invoking your addon in the process breaks it, then your addon is likely the cause.

**Comment by Partixel** [comment]
What I mean is,

the fix for the error only prevents the error occurring, the error still exists in some form though as editing the table in the while loop does not actually propagate the changes

**Comment by FPtje** [comment]
Errors prevented from occurring do not occur.

**Comment by Partixel** [comment]
That's what I'm trying to say, the error is only suppressed with that fix, it seems whatever was causing the error, stack corruption, gc, etc, also causes any changes to the table to not actually apply

**Comment by Partixel** [comment]
Infact, I think it is corrupting the entire stack, the tab menu doesn't work correctly either..

**Comment by Partixel** [comment]
Don't worry, I'll sort it out.

**Comment by Partixel** [comment]
Found a problem, when removing a job with DarkRP.removeJob(i) it doesn't reduce jobcount

**Comment by Partixel** [comment]
line 682 of darkrp/gamemodes/modules/base/sh_createitems.lua
add:
jobcount = jobcount - 1

**Comment by Partixel** [comment]
FPtje, when you tested the issue with the table not sorting, were you adding new jobs after the jobs.lua had already been loaded or were you only changing the jobs.lua?

**Comment by FPtje** [comment]
Test: re-adding jobs to categories with `DarkRP.addToCategory(RPExtraTeams[TEAM_...], "jobs", "Citizens")`

"go" in the next pastes means that the team is moved upwards.

Citizen is moved to the top:
```
item.name	Citizen
5	go	Medic
4	go	Hobo
3	go	Gun Dealer
2	go	Citizen
```
Hobo is moved to above the previous hobo, but below the gun dealer:
```
item.name	Hobo
6	go	Medic
5	go	Hobo
4	stop	Gun Dealer
```

It works.

**Pull request closed without merging**
