### PR TITLE
Replace #RPExtraTeams by jobCount

### PR DESCRIPTION
**Pull request by JarosLucky**
In the basic essence, in this context, it has an equal role, but what was is an unnecessary expensive action that can be avoided

### CODE REVIEW

**Comment by FoksVHox** [comment]
This could be a breaking change, as there are some addon that uses `#RPExtraTeams`

**Comment by FPtje** [comment]
Yeah, I'm not sure why there's a separation between `#RPExtraTeams` and the manual job count, but it might indeed break something if there is job removing in between the job creation calls.

Besides, I wouldn't call a `#RPExtraTeams` unnecessarily expensive.

**Comment by JarosLucky** [comment]
Maybe then we made .team = Team?

пт, 19 февр. 2021 г., 16:52 Falco Peijnenburg <notifications@github.com>:

**Comment by mcNuggets1** [comment]
Didn't you once say. One should use table.Count for RPExtraTeams?

**Pull request closed without merging**
