### PR TITLE
Fix setaccess offline player

### PR DESCRIPTION
**Pull request by chelog**
How the world didn't tell you for so long?
Does that mean nobody (except my friend) uses FAdmin? It's very important feature and this fix is extremely simple. Hope this helps someone.

### CODE REVIEW

**Comment by FPtje** [comment]
Could it have something to do worth older and newer steam ids? What's your steam id? If it's in a different format than, say, mine (STEAM_0:0:8944068) you might indeed need six args instead of five.

**Comment by FPtje** [comment]
Oh wait, the sixth argument is always used in that case for the group name.

**Comment by FPtje** [comment]
And no, no one did tell me.

It's pretty funny, many of the real bugs that get reported nowadays are ones that have gone unnoticed for years and years. In this case, I reckon people might have hit it, but just put quotes around the steam id making it work again.

**Comment by chelog** [comment]
No, it would work for online players only. I tried both ways and did not succeed on setting offline player's rank. It just says "Player not found".

**Comment by MrBrax** [comment]
i used to do it via raw mysql queries, i just thought it wasn't implemented :ok_hand:

**Pull request merged**
