### PR TITLE
Now *AvatarLarge* does not exist.

### PR DESCRIPTION
**Pull request by cardentity**

### CODE REVIEW

**Comment by Colefrick** [comment]
Does this patch fix the over sized avatars in the scoreboard?

**Comment by FPtje** [comment]
No

**Comment by Colefrick** [comment]
Ok thanks.

Is the over sized avatars a server side error or a darkrp error?

**Comment by FPtje** [comment]
It should be your error, that was fixed ages ago. If I'm not mistaken this
pull request removes dead code that resulted from that fix.

**Comment by Colefrick** [comment]
Ok thanks.

**Pull request merged**
