### PR TITLE
"Optimization" of hungermod

### PR DESCRIPTION
**Pull request by Seef0x**

### CODE REVIEW

**Comment by Kefta** [comment]
Lua doesn't evaluate 0 as false. You need to keep the == 0 check.

**Comment by Seef0x** [comment]
Oh my bad, there was always the == 0 check but i had to get confused with the second pull request

**Comment by mcNuggets1** [comment]
I just woke up, but it shouldn't work even after that, because the energy var is substracted a line up.
Meaning, you would use the uneditted var.

**Comment by Seef0x** [comment]
Lol i didn't see
Is caching the calculation and using it on the 2 lines more optimized than re recup?

**Comment by FPtje** [comment]
> Is caching the calculation and using it on the 2 lines more optimized than re recup?

Not really, getting the DarkRPVar is just a table lookup. 

I'll close the issue. Thanks for the attempt at optimisation.

**Comment by Kefta** [comment]
It does save a hashtable lookup and function call so it is marginally more efficient, but you should've fixed the issue I pointed out in time.

**Pull request closed without merging**
