### PR TITLE
Fix server console database checking

### PR DESCRIPTION
**Pull request by Seef0x**

### CODE REVIEW

**Comment by FPtje** [comment]
Thanks for the PR! It looks like the IsValid check should already be covered by the IsSuperAdmin check and the getworld check.

I think I'm missing some context. What problem does this solve?

**Comment by Seef0x** [comment]
Sorry for for lack of detail!

It fixes a lua error if u try to check db with server console

image

**Comment by Seef0x** [comment]
Hmm
Display func will still send a net

**Comment by FPtje** [comment]
Ah, thanks for the detail! Interesting, it looks like the `ply ~= game.GetWorld()` check doesn't work. That one should exit the if-statement before it gets to the superadmin check.

**Comment by Seef0x** [comment]
World check isnt for singleplayer mod?

**Comment by FPtje** [comment]
Did something change in console commands, that instead of ply being `Entity(0)`, it is now `NULL`?

**Comment by Seef0x** [comment]
Hmm no
image

**Comment by FPtje** [comment]
Yeah in con commands, the ply parameter

**Comment by Seef0x** [comment]
Rip
image

**Comment by FPtje** [comment]
Thanks!

**Pull request merged**
