### PR TITLE
Don't get printer position if we can't print

### PR DESCRIPTION
**Pull request by Kefta**
Micro-optimization

### CODE REVIEW

**Comment by FPtje** [comment]
Why

**Comment by Velkon** [comment]
REALLY HELPED MY SERVER LAG
THANKS

**Comment by SwadicalRag** [comment]
velkon is that runescape

**Comment by zerfgog** [comment]
Mi equipo no es lento ahora! ¡Muchas gracias!

**Comment by Velkon** [comment]
falco numbers are like bags of skittles a friday, and i hid cac netmessages from the main program files menu and a D overall wtf??

**Comment by kalis0x** [comment]
why does darkrp not have the largest collection of bad-dragon dildos

**Comment by FPtje** [comment]
And for fucks sake trailing whitespace

**Comment by kalis0x** [comment]
cac minecraft editiion

**Comment by SwadicalRag** [comment]
(these were messages autogenerated by hash.js' markov module, @FPtje)

**Comment by FPtje** [comment]
Could you fucking not

**Comment by zerfgog** [comment]
i can't not

**Comment by FPtje** [comment]
Cunt

**Pull request merged**
