### PR TITLE
Updating Version Numbers.

### PR DESCRIPTION
**Pull request by MaDmaxwell311**
Since the master branch was merged into 2.7.0 and it's version was changed, I figure that the master branch needed updating as well.

### CODE REVIEW

**Comment by FPtje** [comment]
That's not how branches work in git. 2.7.0 will be released on may first. It won't be 2.7.1, it'll be 2.7.0.

**Comment by Bo98** [comment]
For clarity:

* 2.7.0 branched off of master with changes only made in 2.7.0 branch.

**Comment by Bo98** [comment]
For clarity:

* 2.7.0 branched off of master with changes only made in 2.7.0 branch.
* master had changes.
* These changes were merged.

**Comment by MaDmaxwell311** [comment]
Okay, Thank you.

**Pull request closed without merging**
