### PR TITLE
Update simplerr.lua

### PR DESCRIPTION
**Pull request by DARKRPISSHITFIXTHISUPDATE**
I FIX PROBLEM WITH AUTOREFRESHFRESH

### CODE REVIEW

**Comment by HDG-MrDeeJay** [comment]
its sad that people like you can read LUA.

**Comment by LetsRaceBwoi** [comment]
can we please ban this guy from the repo? he's making shit pull requests.  a troll, in an nutshell - it is unnecessary.  he's also using a throwaway account, so we'll have to contact GitHub to get his IP banned 'n' that.

**Comment by FPtje** [comment]
Long gone mate

**Comment by immibis** [comment]
Any chance of having an option to disable simplerr globally, for people who can read normal Lua errors?

**Comment by HDG-MrDeeJay** [comment]
Simplerr is better: People who can read lua errors can use this just as 
well if not better than without simplerr.

**Comment by immibis** [comment]
@HDG-MrDeeJay The only bad thing about it is that it breaks auto-refresh.

**Comment by HDG-MrDeeJay** [comment]
Have you even seen the code this pr tried to edit? I think the text "#NoSimplerr#" seems interesting, don't you?

**Comment by FPtje** [comment]
Explicitly not possible, because addons would disable it and break it for the people who need it

**Pull request closed without merging**
