### PR TITLE
Only damage entities with stunstick, when they are illegal

### PR DESCRIPTION
**Pull request by mcNuggets1**

### CODE REVIEW

**Comment by Kefta** [comment]
I think it should still hurt the hit player

**Comment by mcNuggets1** [comment]
it should still do damage.
the damage for a player is being handled a few lines above.

**Comment by FPtje** [comment]
All entities that the player can damage should be able to get damaged. There will probably be some printers that break with this PR.

**Comment by mcNuggets1** [comment]
Maybe reduce the damage to actually 10 and not entirely break anything as you can just instabreak everything, no matter the health.

**Pull request closed without merging**
