### PR TITLE
Added hook "playerWeaponsChecked"

### PR DESCRIPTION
**Pull request by BillyOnWiiUIn144p**
Requested for logging systems.
Include the results as an argument too if you would like.

### CODE REVIEW

**Comment by FPtje** [comment]
Document the hook in a hook stub

**Comment by BillyOnWiiUIn144p** [comment]
Pushed commit for hookstub in modules/police/sv_interface.lua

**Comment by fruitwasp** [comment]
Get rid of the ```on``` too? https://github.com/FPtje/DarkRP/pull/1996

**Comment by fruitwasp** [comment]
Also, change to ```hook.Call``` and don't forget about a space after the commas

**Comment by fruitwasp** [comment]
Change ```GAMEMODE``` to ```nil```

**Comment by fruitwasp** [comment]
I should have listed all improvements in one comment. Sorry to whoever received emails about this PR.

**Comment by FPtje** [comment]
Also I don't have spaces around parentheses.

**Comment by FPtje** [comment]
Note that I switched the arguments around of the weapon checking player and the target.

http://wiki.darkrp.com/index.php/Hooks/Server/playerWeaponsConfiscated
http://wiki.darkrp.com/index.php/Hooks/Server/playerWeaponsReturned
http://wiki.darkrp.com/index.php/Hooks/Shared/playerWeaponsChecked

**Pull request merged**
