### PR TITLE
Set default player scale to 72, not 64

### PR DESCRIPTION
**Pull request by DaaOtt**
This is GMod's default, prediction will work now

### CODE REVIEW

**Comment by FPtje** [comment]
I remember it always being 64. Where are you getting this from?

**Comment by DaaOtt** [comment]
https://developer.valvesoftware.com/wiki/Dimensions#Overhead_Obstacle_Height

further proof incoming

**Comment by FPtje** [comment]
Second question, why does prediction break when it's not on the default value?

**Comment by DaaOtt** [comment]
https://a.pomf.se/gisfob.mp4

**Comment by HDG-MrDeeJay** [comment]
oh boy, this bug.

**Comment by DaaOtt** [comment]
Sandbox: https://a.pomf.se/rnnimg.mp4

**Comment by FPtje** [comment]
w/e

**Pull request merged**
