### PR TITLE
Some doc realm fixes

### PR DESCRIPTION
**Pull request by Bo98**

### CODE REVIEW

**Comment by FPtje** [comment]
will regenerate wiki later.

**Comment by Bo98** [comment]
Did you regenerate the wiki? I see the old pages removed but no new ones.

**Comment by FPtje** [comment]
not yet, no

2015-03-15 21:06 GMT+01:00 Bo Anderson <notifications@github.com>:

**Comment by Bo98** [comment]
Ah, I assumed the old pages being removed was you regenerating it.

**Pull request merged**
