### PR TITLE
Improved DarkRP.isEmpty

### PR DESCRIPTION
**Pull request by fruitwasp**

### CODE REVIEW

**Comment by FPtje** [comment]
There's only one line change, why is the entire function weirdly indented?

**Comment by fruitwasp** [comment]
Linter warnings

**Comment by FPtje** [comment]
So the linter forces you to change 4 spaces into 2?

**Comment by fruitwasp** [comment]
Not forced, just a warning

**Comment by FPtje** [comment]
glualint only warns when you use both tabs and spaces for indentation. Not when you use two spaces and/or four.

**Comment by fruitwasp** [comment]
Believe me or not. Anyway, reverted

**Comment by FPtje** [comment]
I'm the author of glualint. It only warns for inconsistent use of tabs and spaces.

**Comment by fruitwasp** [comment]
I know you are. As I said, believe me or not. Leave it, please.

**Pull request merged**
