### PR TITLE
Stunstick Fix

### PR DESCRIPTION
**Pull request by 00875**
This can be merged

### CODE REVIEW

**Comment by FPtje** [comment]
Why did you change SWEP:DrawWorldModelTranslucent to  SWEP:DrawWorldModel

**Comment by 00875** [comment]
@FPtje What changed if call DrawModel() before and after?

**Comment by FPtje** [comment]
It's your pull request, you tell me! Do you even know what you're doing?

**Comment by 00875** [comment]
I'll see nothing changed. So thats good!

**Comment by Bo98** [comment]
I moved it after for a reason. It's to do with Z ordering.

Anyway why do we need the attachment bit? Did you find a model that does not have a right hand but has a right hand animation attachment?

**Comment by Partixel** [comment]
I believe he said it was to prevent erroring if the player has the "ERROR" playermodel

**Comment by Bo98** [comment]
The fix for that is a simple nil check for LookupBone, nothing else here is necessary as I am aware of.

**Comment by Partixel** [comment]
Well, he's clearly not the smartest of the bunch, it would probably be best if someone helped him along because this gets drawn out over several days.

**Comment by Partixel** [comment]
```lua
function SWEP:DrawWorldModelTranslucent()
	if CurTime() <= self:GetLastReload() + 0.1 then
		if !IsValid( self:GetOwner():LookupBone("ValveBiped.Bip01_R_Hand") ) then return end
		local bonePos, boneAng = self:GetOwner():GetBonePosition(self:GetOwner():LookupBone("ValveBiped.Bip01_R_Hand"))
		if bonePos then
			local pos = bonePos + (boneAng:Up() * -16) + (boneAng:Right() * 3) + (boneAng:Forward() * 6.5)
			render.SetMaterial(Material("sprites/light_glow02_add"))
			render.DrawSprite(pos, 32, 32, Color(255, 255, 255))
		end
	end
	self:DrawModel()
end
```
Would that do?

**Comment by Bo98** [comment]
Bones don't have an IsValid method so just a simple nil check will be what's needed here.

While returning would be nicer here too, it prevents DrawModel being called which is why I avoided it for bonePos. Does lead to the [pyramid problem](https://github.com/FPtje/DarkRP/commit/81039b7b388ba4c53ce37767e57c076836ff54a1) though.

```lua
if a then
	if n then
		if d then
			if _ then
				if p then
					if y then
						if r then
							if a then
								if m then
									if i then
										if d then
											if s then
												if _ then
													if a then
														if r then
															if e then
																if _ then
																	if n then
																		if o then
																			if t then
																				if _ then
																					if n then
																						if i then
																							if c then
																								if e then
																									if _ then
																										if c then
																											if o then
																												if d then
																													if e then
																														-------|>-|o
																													end
																												end
																											end
																										end
																									end
																								end
																							end
																						end
																					end
																				end
																			end
																		end
																	end
																end
															end
														end
													end
												end
											end
										end
									end
								end
							end
						end
					end
				end
			end
		end
	end
end
```

**Comment by Partixel** [comment]
Updated my original comment with a nil check + DrawModel(), will that do?

**Comment by Bo98** [comment]
Sure, don't need the `var == nil` though, `nor var` is the normal way to do it. If you'd like me being picky you can make the LookupBone line store to a variable (eg. boneIdx) for less code duplication.

**Comment by Partixel** [comment]
```nor var``` Righty

**Comment by Partixel** [comment]
I'll make a pr with the change

**Comment by Partixel** [comment]
#1966

**Pull request closed without merging**
