### PR TITLE
Optimisations around colors

### PR DESCRIPTION
**Pull request by tochnonement**

### CODE REVIEW

**Comment by Kefta** [comment]
Looks good as is, why'd you close?

**Comment by tochnonement** [comment]
> Looks good as is, why'd you close?

Uhh, I didn't pass all the checks, so I've decided to make a new pull request

**Comment by WilliamVenner** [comment]
You can just push to the branch to make changes.

**Comment by tochnonement** [comment]
Idk how to make it properly, so I created a new pull request one last time, finally I've passed all the checks
https://github.com/FPtje/DarkRP/pull/3161

**Pull request closed without merging**
