### PR TITLE
Potentially fixed random rank resets.

### PR DESCRIPTION
**Pull request by 00875**
Thats worked on my server for ages, so i create a pull request

### CODE REVIEW

**Comment by FPtje** [comment]
I won't put arbitrary retries in functions that store something in the database.

**Comment by 00875** [comment]
Basicly: Something changes rank quicker than FAdmin to user and back to admin, and that writes to DB faster than FAdmin reads.

**Comment by FPtje** [comment]
This pr won't solve that. CAMI will.

**Comment by Partixel** [comment]
CAMI will solve all of our problems

**Pull request closed without merging**
