### PR TITLE
Update sv_jobs.lua

### PR DESCRIPTION
**Pull request by cardentity**

### CODE REVIEW

**Comment by FPtje** [comment]
What are you fixing here?

**Comment by cardentity** [comment]
earlier: if limit is one of the teams you cannot swap

**Comment by cardentity** [comment]
e.g, earlier, you can't swap mayor and citizen, because mayor limit is 1

**Comment by TheEMP** [comment]
But then it would allow you to bypass all other checks that the job may have. Your fixing one problem and creating a lot more.

**Comment by FPtje** [comment]
Yup, this bypasses a ton of checks.

**Pull request closed without merging**
