### PR TITLE
Syntax fix

### PR DESCRIPTION
**Pull request by aStonedPenguin**
uniformityIs aGreatThing

### CODE REVIEW

**Comment by Kefta** [comment]
Remove the GM argument

**Comment by aStonedPenguin** [comment]
ohShit iForgot

**Comment by HDG-MrDeeJay** [comment]
gg

**Comment by Bo98** [comment]
If you want to do this then at least do it in init.lua too.

**Comment by Bo98** [comment]
Doesn't this break the GM function though? While hook.Run DOES call the GM function, I believe it doesn't do this until GAMEMODE exists.

**Comment by Partixel** [comment]
hook.Run != hook.Call, how is this a syntax fix?

**Comment by FPtje** [comment]
Hook.Run somehow didn't work. It should, but it didn't. I don't know why, but I went "fuck it" and used hook.Call.

**Comment by Bo98** [comment]
Pretty sure it's because hook.Run uses GAMEMODE which is nil here.

**Comment by FPtje** [comment]
Yeah gmod.GetGamemode or something. Hook.Call it is.

**Pull request closed without merging**
