### PR TITLE
Changed ents.Create max entity detection to use ents.GetEdictCount

### PR DESCRIPTION
**Pull request by Kefta**
This is how it's done internally, so this will be the most accurate.

### CODE REVIEW

**Comment by FPtje** [comment]
The function doesn't exist on the wiki. Was it added in an update? Will it be?

**Comment by Kefta** [comment]
This function exists in the main branch. I have created the wiki page: http://wiki.garrysmod.com/page/ents/GetEdictCount

**Comment by FPtje** [comment]
Then I'll merge when it's live. Thanks!

**Comment by Kefta** [comment]
It is currently live -- it was an undocumented change in the July 2017 update

**Comment by FPtje** [comment]
Super!

**Pull request merged**
