### PR TITLE
changes "You need not" to Don't.

### PR DESCRIPTION
**Pull request by ZEROPOINTBRUH**
changes "You need not" to Don't. It's that simple...

### CODE REVIEW

**Comment by FPtje** [comment]
"you need not" is just a little more formal, what's wrong with it?

**Comment by ZEROPOINTBRUH** [comment]
"You need not worry about updating this file." sounds kinda wrong and messy.
"Don't worry about updating this file." sounds proper.

**Comment by DarthPoint** [comment]
You both are wrong mortals it's actually thou shall not worry

**Comment by GuDevion** [comment]
Thy worries shall be abolished!

**Comment by DarthPoint** [comment]
FOOL! its actually  thee should not w'rry

**Comment by GuDevion** [comment]
INADEQUATE! you jest! Thy proper converse for our discourse shall be, "Take formal disregard for any worries thy possesses."

**Comment by DarthPoint** [comment]
You  absurd foolish delinquent! It is actually take your worries off of thy head

**Comment by ZEROPOINTBRUH** [comment]
Abominent Fools! "Ye shan't w'rry. Thee needeth not w'rry about updating this fileth."

**Comment by DarthPoint** [comment]
Surely you jest sire! For tis is our responsibility to be educative scholars?

**Comment by FlorianLeChat** [comment]
Make relevant and useful comments, dozens of people receive notifications for each new post... 😐

**Pull request merged**
