### PR TITLE
Improving code base

### PR DESCRIPTION
**Pull request by Aka7tsu4**
Using gluaint on all lua files.
remove lua comments
https://fptje.github.io/glualint-web/ 

that's a good idea no? (much server use darkrp they need to be optimized) *-*

### CODE REVIEW

**Comment by Bo98** [comment]
I think you changed the line endings for all the files.

https://github.com/sugarcrm/sugarcrm_dev/wiki/Line-Ending-issues-on-Windows-with-git

(and also don't use the default Notepad since it can't handle some line endings)

**Comment by Bo98** [comment]
That said, I'm not sure how removing _all_ Lua comments is an improvement.

**Comment by Aka7tsu4** [comment]
i also changed umsg with net
and suppressing useless space

**Comment by FPtje** [comment]
I don't see the point of this change. Glualint's pretty printer is great, but not perfect. It cannot get the layout right 100% because many layout things depend on the meaning of code. For example, sometimes you'd want to align code [(e.g. here)](https://github.com/FPtje/DarkRP/blob/master/entities/weapons/door_ram/shared.lua#L183-L190) to make it more clear what it does.

Besides, changes in layout aren't an improvement. In the best case the layout is just different. In the worst case it messes up original layout or even introduces bugs. I'm still not 100% sure that the pretty printer has no edge cases where it changes the semantics of code.

**Pull request closed without merging**
