### PR TITLE
Update cl_init.lua

### PR DESCRIPTION
**Pull request by MoskalykA**

### CODE REVIEW

**Comment by FPtje** [comment]
This can't be right. What are you doing?

**Comment by TomDotBat** [comment]
oPtImIsAtIoN BrO WhAt Do YoU ThInK?

**Comment by MoskalykA** [comment]
I'm thinking of optimization.

**Comment by FPtje** [comment]
Not drawing things makes things faster in the same way not running a gamemode does. Sure, faster, but you kinda lose something along the line.

**Pull request closed without merging**
