### PR TITLE
Optimizations around colors

### PR DESCRIPTION
**Pull request by tochnonement**
Hey, sorry for creating a bunch of pull requests, I think this time I didn't touch any files, which have their own repository, so I'll be able to pass all checks.

### CODE REVIEW

**Comment by FlorianLeChat** [comment]
Your additional rendering optimizations should be moved to an another pull request

**Comment by Kefta** [comment]
I'd also like to see some benchmarks on those trace optimisations to see how much they really help.

**Comment by FPtje** [comment]
Those trace optimisations are visible for the end user. Specifically, they delay the showing of some info by up to 100ms. User experience shouldn't suffer under optimisations.

**Comment by tochnonement** [comment]
> I'd also like to see some benchmarks on those trace optimisations to see how much they really help.

I compared the difference in hook performance by [DBugr](https://github.com/oubliette32/DBugR)
Screenshots:
- [Before](https://i.imgur.com/b2cUwRL.png)
- [After](https://i.imgur.com/ZwBbxJt.png)

Also here's the direct comparison between functions using [this library](https://github.com/tochnonement/gbench)
```
= BENCHMARK =
LuaJIT 2.1.0-beta3: Enabled
Calls: 1,000,000
Arch: x64
Results: 
1. "DarkRP.getCachedTrace":	0.00029929999982414
2. "GetEyeTrace":	0.30854139999974 (102987.67129336% slower)
```

**Comment by FPtje** [comment]
Thanks for the pull request!

**Comment by Kefta** [comment]
> > I'd also like to see some benchmarks on those trace optimisations to see how much they really help.
> 
> I compared the difference in hook performance by [DBugr](https://github.com/oubliette32/DBugR) Screenshots:
> 
> * [Before](https://i.imgur.com/b2cUwRL.png)
> * [After](https://i.imgur.com/ZwBbxJt.png)
> 
> Also here's the direct comparison between functions using [this library](https://github.com/tochnonement/gbench)
> 
> ```
> = BENCHMARK =
> LuaJIT 2.1.0-beta3: Enabled
> Calls: 1,000,000
> Arch: x64
> Results: 
> 1. "DarkRP.getCachedTrace":	0.00029929999982414
> 2. "GetEyeTrace":	0.30854139999974 (102987.67129336% slower)
> ```

I meant one showing realtime performance, where you can see how many times it's realistically being called per frame.

**Pull request merged**
