### PR TITLE
After Cleanup setup doors

### PR DESCRIPTION
**Pull request by 00875**
After that fix:

### CODE REVIEW

**Comment by fruitwasp** [comment]
I think it belongs in the doorsystem module.

**Comment by Bo98** [comment]
It's calling local functions so it has to be there.

**Comment by FPtje** [comment]
What happens if you remove the timer?

**Comment by NamefuI** [comment]
"was puted on your bank account" ayy lmao

**Comment by 00875** [comment]
@FPtje for some reasons it sometimes don't work without timer.

**Pull request merged**
