### PR TITLE
APAnti now fixed

### PR DESCRIPTION
**Pull request by LuaTenshi**
APAnti is now fixed no need to break some parts of it. https://github.com/LuaTenshi/GLua/commit/3eee8c78cbec4c1c5cbf56fe297ba67cf535a4f9

Also no need to be mean and break other peoples code and insult them over the internet. You hurt my feelings and I am gonna tell my mommy on you.

### CODE REVIEW

**Comment by HDG-MrDeeJay** [comment]
>Untested

**Comment by LuaTenshi** [comment]
@HDG-MrDeeJay There is no reason it should not work the code changes were very simple. I pretty much removed the stuff that he wanted gone but left a variable for people to enable it if they want to for some reason mess around with my idea. So pretty much its the same thing as the "fuck up" just a nicer cleaner version and less insults. :p

**Comment by HDG-MrDeeJay** [comment]
But the insults are what make it funny

**Comment by LuaTenshi** [comment]
I guess so... but I prefer to keep it clean. I have tested this edit and it works, yay.

**Comment by FPtje** [comment]
People don't immediately update addons. This needs to stay in to help people who don't immediately update their addons.

**Comment by HDG-MrDeeJay** [comment]
Its getting close to issue 2000. Inb4 falco cheats again

**Comment by FPtje** [comment]
2000 issues? It's a bit early for that, and what do you mean by cheating?

**Comment by HDG-MrDeeJay** [comment]
#1000 Happy birthday DarkRP. Description: I cheated.

**Comment by HDG-MrDeeJay** [comment]
And its close enough, we are only 83 issues away from it. I've been waiting for it since about issue 1800.

**Comment by FPtje** [comment]
2000 would be have been an arbitrary if humans had 8 fingers instead of 10.

**Comment by HDG-MrDeeJay** [comment]
But we do have 8 fingers.

We also have 2 thumbs.

**Comment by Bo98** [comment]
Wow #1000 was 2013?

**Comment by FPtje** [comment]
Yes, people report fewer issues.

**Pull request closed without merging**
