### PR TITLE
It is time we merge darkrp facepunch edition

### PR DESCRIPTION
**Pull request by aStonedPenguin**
I want my shekels

### CODE REVIEW

**Comment by NotSoSuper** [comment]
:+1:

**Comment by aStonedPenguin** [comment]
:+1:

**Comment by KingofBeast** [comment]
:+1: Best gamemode I've ever had the privilege of playing.

**Comment by thelastpenguin** [comment]
:+1:

**Comment by melichior** [comment]
:-1:

**Comment by melichior** [comment]
whoops i mean :+1:

**Comment by zerfgog** [comment]
:thumb:

**Comment by NotSoSuper** [comment]
This will make DarkRP fresh again!

**Comment by melichior** [comment]
image

**Comment by HDG-MrDeeJay** [comment]
It's not that funny.

**Comment by HDG-MrDeeJay** [comment]
this should be merged with lightrp

**Comment by HDG-MrDeeJay** [comment]
Are there actually servers running FPRP?

**Comment by LetsRaceBwoi** [comment]
what the fuck

**Comment by grimesx** [comment]
+support guys

**Comment by LetsRaceBwoi** [comment]
wat

**Comment by NotSoSuper** [comment]
if we replace advert with billboards @Fptje will you merge pls?

**Comment by Shigbeard** [comment]
while ur at it replace /cp with a link to cp.

**Comment by NotSoSuper** [comment]
cheese pizza, civil protection? Make up your mind @Shigbeard

**Comment by Shigbeard** [comment]
theres another cp you havent thought of.

**Comment by LetsRaceBwoi** [comment]
cheese pants

**Pull request closed without merging**
