### PR TITLE
playerPickedUpCheque, playerToreUpCheque, playerDroppedCheque, playerDroppedMoney

### PR DESCRIPTION
**Pull request by BillyOnWiiUIn144p**
- playerPickedUpCheque
- playerToreUpCheque
- playerDroppedCheque
- playerDroppedMoney
- Added money entity to playerPickedUpMoney
- Moved some hookstubs to where they're called
- Added hookstubs for new hooks

For logging.

### CODE REVIEW

**Comment by HDG-MrDeeJay** [comment]
Would it not be a million times better to just have a hook whenever the 
wallet changes, and specify what the source or reason for this change is.

This way you would not only log Cheques and Cash, you would also log any 
addon, plugin or script that made any adjustment to the players wallet, 
which would be far more effective than just logging cheques and money. 
The only time I'd see that as unnecessary is when someone uses darkrp 
add/setmoney <player> <amount>... as that is logged anyway.

**Comment by BillyOnWiiUIn144p** [comment]
Yes, you could do that but you'd have to keep the old hooks to keep older addons working.

I would definitely like that way but legacy seems best from here.

**Comment by HDG-MrDeeJay** [comment]
Perhaps in 2.7

**Comment by FPtje** [comment]
You would have to make a reason system. How would you represent a reason? Some string? An enumeration? Just a number? What about addons that change wallet count, should they keep telling DarkRP why they changed wallet counts? If you use enums or numbers, you'd have to make some function to register enums or get some unique number. 

This gets really ugly really fast.

**Comment by BillyOnWiiUIn144p** [comment]
Agreed, especially for older addons.

**Pull request merged**
