### PR TITLE
Don't use hands with viewmodel which don't support them

### PR DESCRIPTION
**Pull request by roboderpy**
I got a truck of issue reports about floating hands in PPM/2 and now you can assume i went completely mad from that.

### CODE REVIEW

**Comment by FPtje** [comment]
What is PPM/2?

**Comment by FPtje** [comment]
Seriously, what is that?

**Comment by Kefta** [comment]
I mean, UseHands should still be false regardless. v_stunbaton is a v_model.

**Comment by roboderpy** [comment]
Some brony stuff

**Pull request merged**
