### PR TITLE
Some typically bad Shigbeard code for custom /cr aliases.

### PR DESCRIPTION
**Pull request by Shigbeard**
It works, should address #2420 

I'm disgusted in my usage of `timer.Simple(1, function() ... end)` but it works.

### CODE REVIEW

**Comment by FPtje** [comment]
Are you out of your mind!? This is the worst idea for a config option!

**Comment by Shigbeard** [comment]
That's just me! King of shitty ideas.

**Comment by FPtje** [comment]
Be a dear and stick your self loathing up your ass

**Comment by Shigbeard** [comment]
Ok.

**Comment by FPtje** [comment]
Thank you

**Comment by FPtje** [comment]
For fuck's sake, what did I tell you!?

**Comment by Shigbeard** [comment]
didn't think it would show up in the history, I'll just step away from 
github now.

**Comment by FPtje** [comment]
You're depressed, talk to someone.

**Comment by Shigbeard** [comment]
Thank you, I wasn't going to accept "You're depressed" from myself. I needed someone to tell me that.

And I'm sorry for shitting up your repository.

**Pull request closed without merging**
