### PR TITLE
added chat command alias sellalldoors

### PR DESCRIPTION
**Pull request by fruitwasp**
unownalldoors is existing command

### CODE REVIEW

**Comment by FPtje** [comment]
You don't need to re-declare the command if you use `chatCommandAlias`

**Comment by fruitwasp** [comment]
removed that and squashed commits

**Comment by Bo98** [comment]
Shouldn't the `DarkRP.chatCommandAlias` call be shared rather than just serverside? Like it is now looks like you would not get the clientside benefits from declaring chat commands (F1 menu).

**Comment by fruitwasp** [comment]
you're right, I will move it.

I doubt my decision to use `chatCommandAlias` is the right one though, as most command aliases are defined and declared as new chat commands. This change makes the code inconsistent.

Example:

jailpos: https://github.com/FPtje/DarkRP/blob/a20464ac789824b26df1aad2c9c3834d6f702b30/gamemode/modules/positions/sh_commands.lua#L22
setjailpos: https://github.com/FPtje/DarkRP/blob/a20464ac789824b26df1aad2c9c3834d6f702b30/gamemode/modules/positions/sh_commands.lua#L28

**Comment by FPtje** [comment]
If it prevents duplicate code, why not

**Comment by fruitwasp** [comment]
moved chat command alias to shared

**Pull request merged**
