### PR TITLE
Wake up player if he is disconnected

### PR DESCRIPTION
**Pull request by 00875**
I think this is needed

### CODE REVIEW

**Comment by HDG-MrDeeJay** [comment]
I don't think it is. Any issues that could occur from a dc'd player being asleep could easily be resolved with validation of the player entity.

**Comment by 00875** [comment]
No. If player disconnected, he's ragdoll does not deleted

**Comment by Bo98** [comment]
It's worth noting here that the PlayerDiaconnected hook doesn't catch everything last time I checked. If you must use something like it then try the player_disconnect gameevent.

Unless it was fixed but I don't think it was.

**Comment by FPtje** [comment]
Ragdolls are being removed on disconnect just fine for me.

**Pull request closed without merging**
