### PR TITLE
Update link to mysql lib

### PR DESCRIPTION
**Pull request by OctoEnigma**
Because previous thread is closed.

### CODE REVIEW

**Comment by Bo98** [comment]
You should update the text above it to refer to MySQLOO rather than tmysql4 if you're going to do this.

**Comment by FPtje** [comment]
Is that version confirmed to work?

**Comment by FPtje** [comment]
It's not compatible:

> Some important changes between mysqloo9 and mysqloo8 that might cause incompatibilities:
Bigint fields now return as numbers. This might be problematic if you want to use a bigint as the primary key and select it from the server (such as steamid64).
In these cases make sure to cast the bigint to a string in your SQL query like this: SELECT (CAST steamid64 as 'CHAR') as steamid64 FROM ...
Bit fields now return as numbers (0 or 1)

Some work will have to go into making it compatible. I'm not merging this before that's done.

**Comment by Bo98** [comment]
I don't think DarkRP actually retrieves any of the BIGINT fields, but rather just uses them in WHERE clauses. I don't think BIT columns are used either. That's probably why there haven't been any complaints about shit breaking, but testing everything would still be a good idea.

**Pull request closed without merging**
