### PR TITLE
Change several libraries to git submodules

### PR DESCRIPTION
**Pull request by Partixel**
Not necessary but nice to have, no longer have to manually merge changes.'

### CODE REVIEW

**Comment by Bo98** [comment]
Still have to update the commit ID though.

**Comment by Partixel** [comment]
Nevermind, apparently github doesn't support submodules when downloading the zip, nice github, nice :(

**Comment by Bo98** [comment]
Yeah that was going to be my other question.

**Comment by Partixel** [comment]
I could've sworn it worked in the past with addons like evolve but apparently not.

**Comment by FPtje** [comment]
There are more reasons why I avoid submodules. Subtree merging of fpp is
impossible with it and you have to give a special parameter to git when
cloning.

Subtree merging all the way bitches.

**Comment by Partixel** [comment]
All very good points, now excuse me while I go change all of my projects away from submodules...

-cries-

**Comment by HDG-MrDeeJay** [comment]
drama queen

**Comment by Partixel** [comment]
That may or may not be true, @HDG-MrDeeJay , I guess we'll never know.

**Pull request closed without merging**
