### PR TITLE
Added hook onPlayerSay

### PR DESCRIPTION
**Pull request by TheEMP**
As it stands right now there is no way to to alter messages the player
sends in chat. Since DarkRP rips out all the other PlayerSay hooks, this hook is
needed as an alternative.

### CODE REVIEW

**Comment by Velkon** [comment]
I would shitpost, but please add this

**Comment by FPtje** [comment]
All the old chat hooks are called at the start of playerSay, what are you talking about?

**Comment by 00875** [comment]
If override the gmod default one hook, chat will be global, etc.
Without overriding hook:
2015-09-23_16-19_ponyrp r 1 0 10 6 t
With override:
2015-09-23_16-20_garry s mod
2015-09-23_16-20_ponyrp r 1 0 10 6 t
2015-09-23_16-20_garry s mod 2

**Comment by FPtje** [comment]
That doesn't happen to hooks that are added before `InitPostEntity`. Those hooks go through the player chat process. Any string that they return won't be global.

It's probably better to streamline this behaviour and make it that way for hooks added *after* `InitPostEntity` as well.

**Comment by TheEMP** [comment]
Then that's what the problem is, I was adding the PlayerSay hook in the InitPostEntity hook so I could detect if the game mode was DarkRP. Looking more in depth now there are probably better hooks I could use, so I'll use those instead.

**Comment by Velkon** [comment]
I WANT A CLIENTSIDE WAY TO EDIT THE CHAT MESSAGES WITHOUT FUCKING UP THE (OOC) TAGS

**Comment by HDG-MrDeeJay** [comment]
CAPS LOCK IS NOT CRUISE CONTROL FOR COOL

**Comment by Velkon** [comment]
But I'm still cooler than you 
Cooler

**Comment by HDG-MrDeeJay** [comment]
you desperately wish.

**Pull request closed without merging**
