### PR TITLE
Convert umsg to net

### PR DESCRIPTION
**Pull request by FoksVHox**
DarkRP used umsg instead of the net library

### CODE REVIEW

**Comment by FPtje** [comment]
This has been discussed before. We're not doing this because it breaks tons of addons.

**Comment by FoksVHox** [comment]
Examples of addons? And this is pull will secure the future for DarkRP, because who knows when Facepunch is going to remove usermessages.

**Comment by FPtje** [comment]
Every addon that changes how notifications look.

Facepunch isn't going to remove usermessages any time soon, probably never.

See:
https://github.com/FPtje/DarkRP/pull/2860
https://github.com/FPtje/DarkRP/issues/2082
https://github.com/FPtje/DarkRP/pull/1988

**Comment by TomDotBat** [comment]
People just aren't getting the "usermessage", so many have tried but we'll never forget them ;)
kmn

**Pull request closed without merging**
