### PR TITLE
Add policeRequest hook

### PR DESCRIPTION
**Pull request by Down-s**
Added this hook as I'm making an addon that needs to check when a player sends a /999 request.

### CODE REVIEW

**Comment by WilliamVenner** [comment]
Police aren't necessarily combine

**Comment by Down-s** [comment]
> Police aren't necessarily combine

I'm just keeping it consistent with the function name, combine seems to be used interchangeably with police in the code for whatever reason.

**Comment by WilliamVenner** [comment]
Eh there's an additional ambiguity as well, `combineRequest` can be easily read as `combine request`... combining what???!?!?!

**Comment by FPtje** [comment]
Personally I'm against making hooks for every individual chat command. Every chat command could have its own hook, but it's more bloat than it is worth. It's better to override the chat commands or to use these two hooks:

https://darkrp.miraheze.org/wiki/Hooks/Server/canChatCommand

https://darkrp.miraheze.org/wiki/Hooks/Server/onChatCommand

**Pull request closed without merging**
