### PR TITLE
bonePos or attachment (Final Stunstick fix)

### PR DESCRIPTION
**Pull request by 00875**
If model is ERROR or custom it will create error
```
[ERROR] gamemodes/darkrp/entities/weapons/stunstick/shared.lua:92: bad argument #1 to 'GetBonePosition' (number expected, got no value)
  1. GetBonePosition - [C]:-1
   2. unknown - gamemodes/darkrp/entities/weapons/stunstick/shared.lua:92
```
It totally fixes it

### CODE REVIEW

**Comment by FPtje** [comment]
This really looks like a redoing of your previous pr and an undoing of @Bo98's work. What is going on?

**Comment by 00875** [comment]
@FPtje Error has no bones. It creates error. STOP! I don't klnow how to fix it.

**Comment by 00875** [comment]
So this is it

**Comment by FPtje** [comment]
You are not addressing my concerns. Why are you undoing @Bo98's work?

**Comment by 00875** [comment]
I not undoing. It checkups if Bone exist and then doing some. If bone doesn't exists it will lookup attachment.
Now i fix this:
```
function SWEP:DrawWorldModel()
	self:DrawModel()
	if CurTime() <= self:GetLastReload() + 0.1 then
		local bone = self:GetOwner():LookupBone("ValveBiped.Bip01_R_Hand")
		local bonePos, boneAng
		if bone then bonePos, boneAng = self:GetOwner():GetBonePosition(self:GetOwner():LookupBone("ValveBiped.Bip01_R_Hand")) end
		local attachment = self:GetOwner():LookupAttachment("anim_attachment_rh") and self:GetOwner():GetAttachment(self:GetOwner():LookupAttachment("anim_attachment_rh"))
		if bonePos then
			local pos = bonePos + (boneAng:Up() * -16) + (boneAng:Right() * 3) + (boneAng:Forward() * 6.5)
			render.SetMaterial(Material("sprites/light_glow02_add"))
			render.DrawSprite(pos, 32, 32, Color(255, 255, 255))
		elseif attachment then 
			local pos = attachment.Pos + (attachment.Ang:Up() * 16) + (attachment.Ang:Right() * -3) + attachment.Ang:Forward() * 4
			cam.Start3D(EyePos(), EyeAngles())
				render.SetMaterial(Material("sprites/light_glow02_add"))
				render.DrawSprite(pos, 32, 32, Color(255, 255, 255))
			cam.End3D()
		end
	end
end
```

**Comment by Bo98** [comment]
Do you have a model that anim_attachment_rh and NOT Bip01_R_Hand? I very much doubt this. Fair enough for the LookupBone nil check (apparently this is inconsistent to the LookupAttachment behaviour).

Anyway this is undoing things as you are actually basing this pull request off an older commit rather than the latest. Make the pull request again but from the latest commit.

**Pull request closed without merging**
