### PR TITLE
Fix advert notification text

### PR DESCRIPTION
**Pull request by Gyaviste**

### CODE REVIEW

**Comment by FPtje** [comment]
DarkRP's language system is bad, but that would make it worse. With "advert" we have the excuse that it's the command, "advertise" is an English word that would be impossible to translate in another language.

**Comment by Gyaviste** [comment]
Yes, it IS a command
```
GAMEMODE.Config.chatCommandPrefix .. "advertise"
```
in
```
DarkRP.notify(ply, 1, 4, message or DarkRP.getPhrase("unable", GAMEMODE.Config.chatCommandPrefix .. "advertise", ""))
```

**Comment by Bo98** [comment]
@FPtje This is correcting the untranslated command within the message _from_ /advertise to /advert.

**Comment by FPtje** [comment]
Huh, you're right.

The repo's been deleted though.

**Pull request closed without merging**
