### PR TITLE
Add money printer mover thing

### PR DESCRIPTION
**Pull request by Dannelor**
My mom told me she was proud of it

### CODE REVIEW

**Comment by stapler2025** [comment]
wat

**Comment by HDG-MrDeeJay** [comment]
Do i even want to know?

**Comment by HDG-MrDeeJay** [comment]
Ok.. I looked at this turd. Basically it rewrites all of DarkRP, removes all those .txt documents that warn users that editing files is bad and that the forum is where to ask for help.

It also renames DarkRP to fprp.

**Comment by Dannelor** [comment]
Sorry didn't mean to push to here, was tired and meant to push to the forked joke one

**Comment by HDG-MrDeeJay** [comment]
Ah. Well it certainly gave me a laugh, especially rp_backdoor. That was 
a good one, and I'm saving that line for later.

**Comment by HDG-MrDeeJay** [comment]
Wait, question. Is this forked joke rp thing fully functional?

Cause, I would love to trick some friends into installing it

**Comment by Dannelor** [comment]
You can fork and test it to verify yourself as most of the edits are quick and horribly done. But for the most part it's functional

**Comment by HDG-MrDeeJay** [comment]
Sweet.

**Pull request closed without merging**
