### PR TITLE
Delete unnecessary spaces and align variables.

### PR DESCRIPTION
**Pull request by realpack**

### CODE REVIEW

**Comment by realpack** [comment]
Not sure about this. https://github.com/FPtje/DarkRP/pull/2957/commits/d9ae186e49c985e720142964170690cb14536a67#diff-bb06138cdac0ce92fce42f9aed7607beL68-L74

**Comment by Kefta** [comment]
I think it would look best as
```Lua
return IsValid(ent) and ent:isKeysOwnable()
        and (ent:isDoor() and eyepos:DistToSqr(hitpos) < 2000
         or ent:IsVehicle() and eyepos:DistToSqr(hitpos) < 4000)
```

**Comment by FPtje** [comment]
> I think it would look best as
> 
> ```lua
> return IsValid(ent) and ent:isKeysOwnable()
>          and (ent:isDoor() and eyepos:DistToSqr(hitpos) < 2000
>          or ent:IsVehicle() and eyepos:DistToSqr(hitpos) < 4000)
> ```

Nah I think the `or` situation in the PR is clearer

**Comment by Kefta** [comment]
Giving each parentheses it's own line is really wasteful imo.

**Pull request merged**
