### PR TITLE
Add new jail validity check

### PR DESCRIPTION
**Pull request by Kefta**
Fixes https://github.com/FPtje/DarkRP/issues/2780. Don't lock up servers if they can't create a new jail.

### CODE REVIEW

**Comment by mcNuggets1** [comment]
Shouldn't this be fixed in GMod itself or is it just the way the engine works?

**Comment by Kefta** [comment]
I don't know what it's caused by yet, it doesn't happen on my Windows dedi or listen server

**Comment by mcNuggets1** [comment]
I am on linux, it happens there on some rare occasions.

**Comment by FPtje** [comment]
There are a ton of these in DarkRP already. That's just the reality you have to live with when you code Lua in GMod

**Pull request merged**
