### PR TITLE
HUDShouldDraw DarkRP_VoiceChat

### PR DESCRIPTION
**Pull request by bailmast**
The ability to disable the annoying voice chat icon via HUDShouldDraw

### CODE REVIEW

**Comment by Kefta** [comment]
Since you're already editing the file, you should pass self from GM:HUDPaint and use that instead of GAMEMODE in all the local functions.

**Comment by bailmast** [comment]
Do you mean every single one, even GM.Config?

> Since you're already editing the file, you should pass self from GM:HUDPaint and use that instead of GAMEMODE in all the local functions.

**Comment by Kefta** [comment]
self is only predefined in GM functions. You must pass it as an argument to the local functions so that the hook calls can access it.

**Review by FPtje — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
