### PR TITLE
Remove deprecated umsg; Use net library instead

### PR DESCRIPTION
**Pull request by Mattzimann**
I do a PR for this because umsg ist deprecated and will be removed, so at some point you have to switch.
And because I am planning on starting a server and wan't it to be reliable I have changed this for it.

### CODE REVIEW

**Comment by FPtje** [comment]
You're not the first to suggest this. @Kefta Has made a PR before: https://github.com/FPtje/DarkRP/pull/1988

The problem is that many, many addons rely on these usermessages to work. This change would break them. Usermessages are deprecated and inferior to net messages, but there's no way they're going to be removed any time soon. Until we know beyond reasonable doubt that they are indeed going to be removed, I'd rather not break the tons of addons.

Also note that I have tried to change the usermessages of the notification system, but had to revert it here: https://github.com/FPtje/DarkRP/commit/0ea7d028ea3ce17861012cd2371533bee1598b74 because of the enormous backlash I got from shit breaking.

Sorry, I know they're deprecated, but right now the cure is worse than the disease.

**Comment by mcNuggets1** [comment]
Nobody should directly use user messages, instead use a developer function.

**Comment by oninoni** [comment]
What the hell is a developer function?

**Comment by mcNuggets1** [comment]
https://wiki.darkrp.com/index.php/Category:Functions
Functions for direct use as developer.
That's what I called them in all my addons.

**Pull request closed without merging**
