### PR TITLE
Changed trigger for Animation Menu

### PR DESCRIPTION
**Pull request by Neosinos**
Keys won't open the DarkRP Animation Menu anymore when (mostly) wrongly
Left- or Right Clicking. The Menu can now be triggered through pressing
Reload.

### CODE REVIEW

**Comment by FPtje** [comment]
You just moved the problem from clicking to reload. Besides, this is the kind of thing people have grown used to. Things people have gotten used to need a really good reason to change. Otherwise people will just think the feature got removed, not knowing it moved to a different button.

**Comment by Neosinos** [comment]
This is true, but the thing is a huge amount of people is constantly
complaining about this.

eg;
A player is trying to lock his vehicle when someone trys to drive away with
it; he won't be able cause the AnimMenu will pop up everytime he's not near
enough.

Or if someone trys to go into your house, and you quickly try to lock it.
Most of the time, cause the door will rotate, you'll trigger the menu
accidently.

Am Montag, 16. Februar 2015 schrieb Falco Peijnenburg :

**Comment by Neosinos** [comment]
Why have you reopened it?

**Comment by FPtje** [comment]
Good arguments can convince me.

**Comment by Neosinos** [comment]
So you are?

2015-02-18 9:44 GMT+01:00 Falco Peijnenburg <notifications@github.com>:

**Comment by FPtje** [comment]
I still have to look at it. I originally put it on the mouse buttons
because I was afraid people wouldn't find it in the reload menu.

**Comment by Neosinos** [comment]
Thats true. But you could just put this Information in the Keys
Description. I'll change the Pull later when I'll get home.

2015-02-18 10:00 GMT+01:00 Falco Peijnenburg <notifications@github.com>:

**Comment by FPtje** [comment]
http://forum.darkrp.com/threads/should-the-animation-menu-open-on-reload-instead-of-mouse-click.4273/

**Comment by FPtje** [comment]
The vote won by 70%.

**Comment by Bo98** [comment]
This PR is empty though since @Neosinos reverted back messily.

e0b1281

**Comment by FPtje** [comment]
For God's sake neosinos you massive cunt

**Comment by HDG-MrDeeJay** [comment]
Lol its like that one time when I accidentally about 2 commits.

**Pull request merged**
