### PR TITLE
We need to trust the client in this gamemode, like Rust!

### PR DESCRIPTION
**Pull request by Nyaaaa**
We need to trust the client in this gamemode, like Rust!

### CODE REVIEW

**Comment by Neosinos** [comment]
What the actual fuck.

Am Dienstag, 7. April 2015 schrieb Nyaaaa :

**Comment by Nyaaaa** [comment]
This was ment to be for https://github.com/Nyaaaa/fprp but i did it to the wrong branch lol..

**Comment by Neosinos** [comment]
Does the license from DarkRP allow stealing and rebranding it as your own?
Woosh. Didnt know.

Am Dienstag, 7. April 2015 schrieb Nyaaaa :

**Comment by Nyaaaa** [comment]
You're an idiot, It's from https://github.com/aStonedPenguin/fprp/
Clearly you don't look at facepunch: http://facepunch.com/showthread.php?t=1459450

Big words coming from you! :-1:

**Comment by Neosinos** [comment]
Still not sure if the license allows it. No Statement from Falco yet. If
it's OK, ignore my post.

Am Dienstag, 7. April 2015 schrieb Nyaaaa :

**Comment by FPtje** [comment]
The license explicitly forbids the removal of the license.

Put the god damn license back.

**Comment by Neosinos** [comment]
Why is the fact that this guy called me an idiot so funny thaha

Am Dienstag, 7. April 2015 schrieb Falco Peijnenburg :

**Comment by Nyaaaa** [comment]
Because i'm not the owner of the gamemode idiot, lmao, Retard..

**Comment by HDG-MrDeeJay** [comment]
Clearly Marcel and Falco have never been to 4chan more than once.

Nyaaaa is a fisherman. This pull request was his line (whether it was 
intended to be here or not). The contents of the PR is his bait. You are 
all little fishies, throwing your entire body at his bait, and he is 
catching you hook line and sinker.

TL:DR *Just don't respond.*

**Comment by FPtje** [comment]
Fuck off nathan

**Comment by HDG-MrDeeJay** [comment]
Aight, just saying that its not worth your time to look at that joke of 
a fork.

**Comment by FPtje** [comment]
Bullshit, it would be the bee's dislocated knees if they only added the
license

**Comment by HDG-MrDeeJay** [comment]
only because people are acknowledging its shitty existence.

I'll continue pretending it doesn't exist. You can get mad about a 
missing license in a cancerous gamemode fork (which literally was made 
with "find and replace in files" in 10 minutes, 9 of which involved the 
author scratching his balls) of a gamemode that has had real people put 
real effort into a real product.

**Pull request closed without merging**
