### PR TITLE
Fixed lua error

### PR DESCRIPTION
**Pull request by mcNuggets1**

### CODE REVIEW

**Comment by FPtje** [comment]
Rebase, and have it called once, not twice.

**Comment by mcNuggets1** [comment]
I guess you mean localizing it?

**Comment by FPtje** [comment]
Don't call seizereward multiple times in the same function body.

**Comment by mcNuggets1** [comment]
Could you speak non-codish for me, please? :I

**Comment by mcNuggets1** [comment]
Do you mean it should look this way?

**Comment by FPtje** [comment]
No, I can't talk about your code without talking about code

**Comment by mcNuggets1** [comment]
You could just tell me what to do.

I don't know what a function body is.

I actually do Lua for fun, not for business or somewhat.

**Comment by mcNuggets1** [comment]
I guess youre doing it yourself, when youre home.
Sorry, for the mistakes.

**Pull request closed without merging**
